version: "3"
services:
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodata:/data/db
  growthbook:
    image: "growthbook/growthbook:latest"
    ports:
      - "3000:3000"
      - "3100:3100"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://root:password@mongo:27017/growthbook?authSource=admin
      # Proxy settings
      - PROXY_ENABLED=1
      - PROXY_HOST_INTERNAL=http://proxy:3300
      - PROXY_HOST_PUBLIC=http://localhost:3300
      # generate a read-only key in GB UI settings -> api keys or we can use PAT
      - SECRET_API_KEY=secret_readonly_MwrB0uEQvbn8F653rs7wZBLGUpqYsOaeGUIXDVfCXg
    volumes:
      - uploads:/usr/local/src/app/packages/back-end/uploads
  proxy:
    image: "growthbook/proxy:latest"
    ports:
      - "3300:3300"
    environment:
      - GROWTHBOOK_API_HOST=http://growthbook:3100
      - SECRET_API_KEY=secret_readonly_MwrB0uEQvbn8F653rs7wZBLGUpqYsOaeGUIXDVfCXg
    depends_on:
      - growthbook

volumes:
  uploads:
  mongodata: